version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: game_path_planner_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=game_path_planner
    ports:
      - "5433:5432"
    volumes:
      - ./server/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
